# Use official Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy app files to container
COPY . /app

# Install required Python packages
RUN pip install --no-cache-dir streamlit pandas openpyxl

# Expose Streamlit default port
EXPOSE 8501

# Set Streamlit to listen on all network interfaces
ENV STREAMLIT_SERVER_HEADLESS=true
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ENABLECORS=false

# Command to run the app
CMD ["streamlit", "run", "app.py"]
